# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia os arquivos do projeto
COPY . .

# Restaura dependências
RUN dotnet restore

# Publica a aplicação
RUN dotnet publish -c Release -o /app

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .

# Troque SigaApp.dll pelo nome do seu projeto
ENTRYPOINT ["dotnet", "SigaApp.dll"]
